variable "prefix" {}
variable "application" {}
variable "subscription_id" {}
variable "tenant_id" {}
variable "location" {}
variable "virtual_network_name" {}
variable "virtual_network_resource_group_name" {}
variable "route_table_name" {}
variable "subnet" {}
